export const programsData = {
  // ── Strategic HR programmes ────────────────────────────────────────────────
  "strategic-hr-business-partnership": {
    parentSlug: "strategic-hr",
    parentTitle: "Strategic Human Resources, Business Leadership and Management",
    eyebrow: "Certified Programs",
    title: "Strategic HR Business Partnership & Beyond (SHRBP) Certification",
    description: "A 3-day executive SHRBP certification programme to empower senior HR leaders to become strategic boardroom advisors confidently.",
    banner: "/images/solutions/Programs/strategic-hr-banner.jpg",
    subheading: "",
    subtext: "",
    pricingHeading: "Why It's Worth",
    pricingCurrency: "SGD.",
    price: "3850",
    pricingPeriod: "/Person",
    pricingDescription: "By enrolling, you'll earn a respected EIU-Paris credential and learn practical frameworks to help you grow from an HR practitioner into a Strategic Business Partner. You'll develop the business skills to connect people strategy with company goals, turning human capital into a real driver of growth and success.",
    gains: [
      { id: 1, iconSrc: "/images/solutions/strategic-hr/6.svg", text: "Position HR as a strategic business partner" },
      { id: 2, iconSrc: "/images/solutions/strategic-hr/5.svg", text: "Align people strategy with business goals" },
      { id: 3, iconSrc: "/images/solutions/strategic-hr/4.svg", text: "Influence leaders using data-driven insights" },
      { id: 4, iconSrc: "/images/solutions/strategic-hr/3.svg", text: "Build and execute effective workforce strategies" },
      { id: 5, iconSrc: "/images/solutions/strategic-hr/2.svg", text: "Demonstrate measurable business impact" },
      { id: 6, iconSrc: "/images/solutions/strategic-hr/1.svg", text: "Strengthen collaboration to drive talent performance." },
    ],
    focusHeading: "Focuses on Developing",
    focusAreas: [
      { id: 1, iconSrc: "/images/solutions/strategic-hr/1.svg", title: "Strategic HR Alignment", description: "Strategic thinking aligned with business priorities" },
      { id: 2, iconSrc: "/images/solutions/strategic-hr/2.svg", title: "Data-Driven Decision Making", description: "Data-driven HR decision-making for measurable outcomes" },
      { id: 3, iconSrc: "/images/solutions/strategic-hr/3.svg", title: "Influential Leadership & Stakeholders", description: "Leadership influence and effective stakeholder management" },
      { id: 4, iconSrc: "/images/solutions/strategic-hr/4.svg", title: "Performance-Focused Workforce Strategy", description: "Workforce strategies are directly linked to organisational performance" },
    ],
    faqs: [
      { id: 1, question: "Who is this programme for?", answer: "This program is for Senior HR Managers, Heads of HR, and Directors who lead organisational strategy." },
      { id: 2, question: "Is this certification recognised internationally?", answer: "“The program is accredited by the European International University (EIU-Paris), adding value to your professional profile.”" },
      { id: 3, question: "Can I claim this under my corporate training budget?", answer: "Yes, most of our participants are sponsored by their organisations." },
      { id: 4, question: "How long is the programme?", answer: "The programme runs over 3 intensive days, designed to be completed without disrupting your working schedule." },
      { id: 5, question: "I have a different question. Who should I contact?", answer: "Please contact us via email at ceo@globalatd.com for assistance." },
    ],
    facilitator: {
      name: "Prof. Dr. Joel Farnworth",
      role: "Dean of Business and Management Studies, EIU-Paris",
      image: "/images/solutions/strategic-hr/Dr_Joel.png",
      bg: "/images/solutions/strategic-hr/program_facilitator_BG.png",
      expertise: ["Human Resource Management", "Leadership Development", "Managerial Skills Development", "Corporate Strategy Creation and Implementation", "Performance Management", "Strategic HRM"],
      biography: ["Coach and Consultant", "Strategic HR Management", "Impactful Leadership", "Creating and Implementing Corporate Strategy", "Senior Management Advisor"],
    },
    certification: {
      badge: "Recognised Speaker Credentials",
      heading: "Certification\non Successful\nCompletion",
      image: "/images/solutions/strategic-hr/certificate_image.jpg",
      paragraphs: [
        "When you complete the program, you will receive the Strategic HR Business Partner Certification from EIU Paris and the Global Association for Training & Development (GATD).",
        "This certification recognizes your expertise in boardroom-level HR strategy. It shows your commitment to global standards, innovative leadership, and your ability to drive business success through strategic HR management.",
      ],
    },
    pillarHeading: "3 Strategic Pillars",
    pillarBadge: "3 Days",
    pillarDays: [
      { label: "DAY 1", id: "day1" },
      { label: "DAY 2", id: "day2" },
      { label: "DAY 3", id: "day3" },
    ],
    pillarModules: {
      day1: [
        { id: 1, arrowTitle: "Establishing & Delivering Strategic HR", labelPosition: "bottom", sideLabel: "HR Role Evolution", sideDescription: "Exploring the evolving role of HR Business Partnership and strategic HR services" },
        { id: 2, arrowTitle: "Next Generation HR", labelPosition: "top", sideLabel: "Future HR Models", sideDescription: "Discussing administrator, BP, and predictive contributor roles, and creating people strategy" },
        { id: 3, arrowTitle: "The HRBP Role", labelPosition: "bottom", sideLabel: "HRBP Capabilities", sideDescription: "Defining the HRBP role as a generalist and one-stop solution center, emphasizing influence and change facilitation" },
        { id: 4, arrowTitle: "Business Strategies to Performance Deliverables", labelPosition: "top", sideLabel: "Performance Alignment", sideDescription: "Linking business strategy to performance deliverables, KPIs, and commitment" },
      ],
      day2: [
        { id: 1, arrowTitle: "Talent Management & Succession", labelPosition: "bottom", sideLabel: "Organisational Readiness", sideDescription: "Identifying HIPOs, planning the workforce, and securing succession for critical roles ensures a strong talent pipeline" },
        { id: 2, arrowTitle: "People Management", labelPosition: "top", sideLabel: "Leadership Excellence", sideDescription: "Effective leadership combines impactful style, practical L & M examples, clear success indicators, and precise selection criteria" },
        { id: 3, arrowTitle: "Reward Offerings & Management", labelPosition: "bottom", sideLabel: "Compensation Strategy", sideDescription: "Balancing fixed and variable cash options, trending benefits, brand differentiation, and market positioning drives competitive advantage" },
        { id: 4, arrowTitle: "HR Technology and Data", labelPosition: "top", sideLabel: "HR Analytics", sideDescription: "Leveraging current and future tech, HR tools, data dashboards, and metrics aligns workforce insights with business impact" },
      ],
      day3: [
        { id: 1, arrowTitle: "Organisation Development & Change", labelPosition: "bottom", sideLabel: "Organisational Design", sideDescription: "Core OD elements—diversity, engagement, values, and the work experience—drive a truly engaged organisation" },
        { id: 2, arrowTitle: "Current People Challenges & Solutions?", labelPosition: "top", sideLabel: "People Strategy", sideDescription: "Addressing current challenges by focusing on top priorities, implementing targeted solutions, and taking clear first steps" },
        { id: 3, arrowTitle: "Predictive People Analytics", labelPosition: "bottom", sideLabel: "Future Insights", sideDescription: "Key predictions from AI, consultants, participants, and the trainer highlight emerging trends and future directions" },
        { id: 4, arrowTitle: "Human Capital Trends", labelPosition: "top", sideLabel: "Next Normal", sideDescription: "Anticipating likely needs and responses, focusing on flexible work, CSR, engagement, and inclusive HR advice for the upcoming strategic plan" },
      ],
    },
  },

  "business-people-leadership": {
    parentSlug: "strategic-hr",
    parentTitle: "Strategic Human Resources, Business Leadership and Management",
    eyebrow: "Certified Programs",
    title: "Impactful Business and People Leadership",
    description: "Designed for HR and people leaders seeking to elevate their leadership impact, this programme builds the skills to inspire teams, navigate change, and drive organisational performance.",
    banner: "/images/solutions/strategic-hr/prog-2.jpg",
    subheading: "Lead People. Drive Business. Create Impact.",
    subtext: "This certification blends leadership theory with practical application — equipping participants to lead with clarity, empathy, and strategic purpose.",
    focusHeading: "Focuses on Developing",
    focusAreas: [
      { id: 1, iconSrc: "/images/solutions/strategic-hr/1.svg", title: "Leadership Identity & Style", description: "Exploring personal leadership styles and their impact on team performance and culture" },
      { id: 2, iconSrc: "/images/solutions/strategic-hr/2.svg", title: "Inspiring & Motivating Teams", description: "Practical techniques to build highly motivated, high-performing teams" },
      { id: 3, iconSrc: "/images/solutions/strategic-hr/3.svg", title: "Business Acumen for People Leaders", description: "Developing financial literacy and business understanding to drive smart people decisions" },
      { id: 4, iconSrc: "/images/solutions/strategic-hr/4.svg", title: "Stakeholder Influence & Politics", description: "Navigating organisational dynamics and building influence with senior stakeholders" },
      { id: 5, iconSrc: "/images/solutions/strategic-hr/5.svg", title: "Leading Organisational Change", description: "Guiding teams through transformation with clarity, empathy, and structured change approaches" },
    ],
    faqs: [
      { id: 1, question: "Who is this programme for?", answer: "This programme is designed for HR professionals, managers, and senior leaders who want to build advanced expertise and drive meaningful business impact in their organisations." },
      { id: 2, question: "Is this certification recognised internationally?", answer: "Yes. This certification is accredited by EIU-Paris and GATD, recognised globally by leading organisations and professional bodies." },
      { id: 3, question: "Can I claim this under my corporate training budget?", answer: "Yes. Many participants claim this programme under their organisation's Learning & Development or corporate training budget. We can provide documentation to support your application." },
      { id: 4, question: "How long is the programme?", answer: "The programme runs over 3 intensive days, designed to maximise learning outcomes without a long absence from your role." },
      { id: 5, question: "I have a different question. Who should I contact?", answer: "Please contact us via email at ceo@globalatd.com or through our contact form and our team will respond within 24 hours." },
    ],
    facilitator: {
      name: "Prof. Dr. Joel Farnworth",
      role: "Dean of Business and Management Studies, EIU-Paris",
      image: "/images/solutions/strategic-hr/Dr_Joel.png",
      bg: "/images/solutions/strategic-hr/program_facilitator_BG.png",
      expertise: ["Human Resource Management", "Leadership Development", "Managerial Skills Development", "Corporate Strategy Creation and Implementation", "Performance Management", "Strategic HRM"],
      biography: ["Coach and Consultant", "Strategic HR Management", "Impactful Leadership", "Creating and Implementing Corporate Strategy", "Senior Management Advisor"],
    },
    certification: {
      badge: "Recognised Speaker Credentials",
      heading: "Certification\non Successful\nCompletion",
      image: "/images/solutions/strategic-hr/certificate_image.jpg",
      paragraphs: [
        "When you complete the programme, you will receive a globally recognised certification from EIU Paris and the Global Association for Training & Development (GATD).",
        "This certification demonstrates your advanced expertise, commitment to professional excellence, and readiness to lead at the highest levels of your organisation.",
      ],
    },
    pillarHeading: "Programme Pillars",
    pillarBadge: "3 Days",
    pillarDays: [
      { label: "DAY 1", id: "day1" },
      { label: "DAY 2", id: "day2" },
      { label: "DAY 3", id: "day3" },
    ],
    pillarModules: {
      day1: [
        { id: 1, arrowTitle: "Leadership Identity & Style", labelPosition: "bottom", sideLabel: "Leadership Foundations", sideDescription: "Exploring personal leadership styles and their impact on team performance and organisational culture" },
        { id: 2, arrowTitle: "Inspiring & Motivating Teams", labelPosition: "top", sideLabel: "Team Engagement", sideDescription: "Practical techniques to build highly motivated, high-performing teams through purposeful leadership" },
        { id: 3, arrowTitle: "Strategic Communication", labelPosition: "bottom", sideLabel: "Communication Excellence", sideDescription: "Mastering executive communication, storytelling, and influence across all levels of the organisation" },
        { id: 4, arrowTitle: "Decision-Making Under Pressure", labelPosition: "top", sideLabel: "Executive Judgement", sideDescription: "Frameworks for making confident, high-quality decisions in complex and time-critical business situations" },
      ],
      day2: [
        { id: 1, arrowTitle: "Business Acumen for People Leaders", labelPosition: "bottom", sideLabel: "Commercial Thinking", sideDescription: "Developing financial literacy and business understanding to drive commercially smart people decisions" },
        { id: 2, arrowTitle: "Performance Culture Creation", labelPosition: "top", sideLabel: "Culture Leadership", sideDescription: "Building accountability, ownership, and a results-driven culture through consistent leadership behaviours" },
        { id: 3, arrowTitle: "Stakeholder Influence & Politics", labelPosition: "bottom", sideLabel: "Influence Mastery", sideDescription: "Navigating organisational dynamics and building influence with senior stakeholders and peers" },
        { id: 4, arrowTitle: "Coaching & Developing Others", labelPosition: "top", sideLabel: "People Development", sideDescription: "Applying coaching techniques and development frameworks to unlock potential and grow future leaders" },
      ],
      day3: [
        { id: 1, arrowTitle: "Leading Organisational Change", labelPosition: "bottom", sideLabel: "Change Leadership", sideDescription: "Guiding teams and organisations through transformation with clarity, empathy, and structured change approaches" },
        { id: 2, arrowTitle: "Resilience & Wellbeing Leadership", labelPosition: "top", sideLabel: "Sustainable Leadership", sideDescription: "Building personal and team resilience to sustain high performance through adversity and uncertainty" },
        { id: 3, arrowTitle: "Diversity, Equity & Inclusion", labelPosition: "bottom", sideLabel: "Inclusive Leadership", sideDescription: "Embedding DEI principles into leadership practice to build diverse, equitable, and inclusive organisations" },
        { id: 4, arrowTitle: "Leadership Legacy & Impact", labelPosition: "top", sideLabel: "Leadership Purpose", sideDescription: "Defining your leadership legacy and committing to a personal leadership development plan for sustained impact" },
      ],
    },
  },

  "performance-rewards": {
    parentSlug: "strategic-hr",
    parentTitle: "Strategic Human Resources, Business Leadership and Management",
    eyebrow: "Certified Programs",
    title: "Performance Development and Rewards Management",
    description: "This programme equips HR leaders with the frameworks to design, implement, and manage performance and rewards systems that motivate people, retain top talent, and deliver business results.",
    banner: "/images/solutions/strategic-hr/prog-3.jpg",
    subheading: "Build a Performance Culture That Rewards What Matters",
    subtext: "From performance appraisal design to total rewards strategy, participants gain the tools to create systems that are fair, transparent, and aligned with organisational values.",
    focusHeading: "Focuses on Developing",
    focusAreas: [
      { id: 1, iconSrc: "/images/solutions/strategic-hr/1.svg", title: "Performance Management Frameworks", description: "Designing PM systems that drive accountability and measurable results" },
      { id: 2, iconSrc: "/images/solutions/strategic-hr/2.svg", title: "Total Rewards Strategy", description: "Building competitive total rewards packages that attract and retain top talent" },
      { id: 3, iconSrc: "/images/solutions/strategic-hr/3.svg", title: "Variable Pay & Incentive Design", description: "Designing bonus and incentive schemes that drive the right behaviours and outcomes" },
      { id: 4, iconSrc: "/images/solutions/strategic-hr/4.svg", title: "Pay Equity & Compliance", description: "Ensuring fairness, transparency, and legal compliance across all pay practices" },
      { id: 5, iconSrc: "/images/solutions/strategic-hr/5.svg", title: "Recognition & Non-Monetary Rewards", description: "Building meaningful recognition programmes that sustain employee engagement" },
    ],
    faqs: [
      { id: 1, question: "Who is this programme for?", answer: "This programme is designed for HR professionals, managers, and senior leaders who want to build advanced expertise and drive meaningful business impact in their organisations." },
      { id: 2, question: "Is this certification recognised internationally?", answer: "Yes. This certification is accredited by EIU-Paris and GATD, recognised globally by leading organisations and professional bodies." },
      { id: 3, question: "Can I claim this under my corporate training budget?", answer: "Yes. Many participants claim this programme under their organisation's Learning & Development or corporate training budget. We can provide documentation to support your application." },
      { id: 4, question: "How long is the programme?", answer: "The programme runs over 3 intensive days, designed to maximise learning outcomes without a long absence from your role." },
      { id: 5, question: "I have a different question. Who should I contact?", answer: "Please contact us via email at ceo@globalatd.com or through our contact form and our team will respond within 24 hours." },
    ],
    facilitator: {
      name: "Prof. Dr. Joel Farnworth",
      role: "Dean of Business and Management Studies, EIU-Paris",
      image: "/images/solutions/strategic-hr/Dr_Joel.png",
      bg: "/images/solutions/strategic-hr/program_facilitator_BG.png",
      expertise: ["Human Resource Management", "Leadership Development", "Managerial Skills Development", "Corporate Strategy Creation and Implementation", "Performance Management", "Strategic HRM"],
      biography: ["Coach and Consultant", "Strategic HR Management", "Impactful Leadership", "Creating and Implementing Corporate Strategy", "Senior Management Advisor"],
    },
    certification: {
      badge: "Recognised Speaker Credentials",
      heading: "Certification\non Successful\nCompletion",
      image: "/images/solutions/strategic-hr/certificate_image.jpg",
      paragraphs: [
        "When you complete the programme, you will receive a globally recognised certification from EIU Paris and the Global Association for Training & Development (GATD).",
        "This certification demonstrates your advanced expertise, commitment to professional excellence, and readiness to lead at the highest levels of your organisation.",
      ],
    },
    pillarHeading: "Programme Pillars",
    pillarBadge: "3 Days",
    pillarDays: [
      { label: "DAY 1", id: "day1" },
      { label: "DAY 2", id: "day2" },
      { label: "DAY 3", id: "day3" },
    ],
    pillarModules: {
      day1: [
        { id: 1, arrowTitle: "Performance Management Frameworks", labelPosition: "bottom", sideLabel: "PM Systems", sideDescription: "Designing and implementing performance management systems that drive accountability and results" },
        { id: 2, arrowTitle: "Goal Setting & KPI Design", labelPosition: "top", sideLabel: "Objectives Alignment", sideDescription: "Building SMART goal frameworks and KPI systems that align individual performance with business strategy" },
        { id: 3, arrowTitle: "Continuous Feedback Culture", labelPosition: "bottom", sideLabel: "Feedback Systems", sideDescription: "Creating structured feedback processes that accelerate development and sustain high performance" },
        { id: 4, arrowTitle: "Performance Reviews & Calibration", labelPosition: "top", sideLabel: "Review Excellence", sideDescription: "Designing fair, consistent review processes and calibration sessions that build trust and differentiation" },
      ],
      day2: [
        { id: 1, arrowTitle: "Total Rewards Strategy", labelPosition: "bottom", sideLabel: "Rewards Architecture", sideDescription: "Designing competitive total rewards packages that attract, retain, and motivate top talent" },
        { id: 2, arrowTitle: "Compensation Benchmarking", labelPosition: "top", sideLabel: "Market Positioning", sideDescription: "Using market data and benchmarking methodologies to build competitive and equitable pay structures" },
        { id: 3, arrowTitle: "Variable Pay & Incentives", labelPosition: "bottom", sideLabel: "Incentive Design", sideDescription: "Designing variable pay, bonus, and incentive schemes that drive the right behaviours and outcomes" },
        { id: 4, arrowTitle: "Benefits & Wellbeing Programmes", labelPosition: "top", sideLabel: "Employee Benefits", sideDescription: "Building benefits and wellbeing programmes that differentiate your employer brand and support employee needs" },
      ],
      day3: [
        { id: 1, arrowTitle: "Pay Equity & Compliance", labelPosition: "bottom", sideLabel: "Fair Pay", sideDescription: "Conducting pay equity analysis and building frameworks that ensure fairness, transparency, and legal compliance" },
        { id: 2, arrowTitle: "Executive Compensation", labelPosition: "top", sideLabel: "Senior Rewards", sideDescription: "Designing executive pay structures, long-term incentives, and governance frameworks for senior leadership" },
        { id: 3, arrowTitle: "Recognition & Non-Monetary Rewards", labelPosition: "bottom", sideLabel: "Recognition Strategy", sideDescription: "Building meaningful recognition programmes that reinforce culture and sustain employee engagement" },
        { id: 4, arrowTitle: "Rewards Communication", labelPosition: "top", sideLabel: "Rewards Transparency", sideDescription: "Communicating rewards effectively to build trust, understanding, and appreciation across the workforce" },
      ],
    },
  },

  "resourcing-talent-learning": {
    parentSlug: "strategic-hr",
    parentTitle: "Strategic Human Resources, Business Leadership and Management",
    eyebrow: "Certified Programs",
    title: "Resourcing, Talent and Learning Management",
    description: "A comprehensive programme covering the full talent lifecycle — from attraction and selection through development and retention — equipping HR professionals to build future-ready organisations.",
    banner: "/images/solutions/strategic-hr/prog-4.jpg",
    subheading: "Attract, Develop and Retain the Talent That Drives Growth",
    subtext: "Participants develop strategic resourcing frameworks, talent pipeline methodologies, and learning design capabilities that deliver measurable organisational impact.",
    focusHeading: "Focuses on Developing",
    focusAreas: [
      { id: 1, iconSrc: "/images/solutions/strategic-hr/1.svg", title: "Strategic Resourcing & Employer Brand", description: "Attracting top talent with a compelling employer value proposition and structured selection" },
      { id: 2, iconSrc: "/images/solutions/strategic-hr/2.svg", title: "Talent Identification & Succession", description: "Identifying high-potential talent and building robust leadership pipelines" },
      { id: 3, iconSrc: "/images/solutions/strategic-hr/3.svg", title: "Individual Development Planning", description: "Creating personalised growth plans that accelerate capability and career progression" },
      { id: 4, iconSrc: "/images/solutions/strategic-hr/4.svg", title: "Learning Design & Digital L&D", description: "Designing blended learning experiences and leveraging EdTech to scale development" },
      { id: 5, iconSrc: "/images/solutions/strategic-hr/5.svg", title: "Learning Impact & ROI", description: "Measuring learning effectiveness and demonstrating business value to stakeholders" },
    ],
    faqs: [
      { id: 1, question: "Who is this programme for?", answer: "This programme is designed for HR professionals, managers, and senior leaders who want to build advanced expertise and drive meaningful business impact in their organisations." },
      { id: 2, question: "Is this certification recognised internationally?", answer: "Yes. This certification is accredited by EIU-Paris and GATD, recognised globally by leading organisations and professional bodies." },
      { id: 3, question: "Can I claim this under my corporate training budget?", answer: "Yes. Many participants claim this programme under their organisation's Learning & Development or corporate training budget. We can provide documentation to support your application." },
      { id: 4, question: "How long is the programme?", answer: "The programme runs over 3 intensive days, designed to maximise learning outcomes without a long absence from your role." },
      { id: 5, question: "I have a different question. Who should I contact?", answer: "Please contact us via email at ceo@globalatd.com or through our contact form and our team will respond within 24 hours." },
    ],
    facilitator: {
      name: "Prof. Dr. Joel Farnworth",
      role: "Dean of Business and Management Studies, EIU-Paris",
      image: "/images/solutions/strategic-hr/Dr_Joel.png",
      bg: "/images/solutions/strategic-hr/program_facilitator_BG.png",
      expertise: ["Human Resource Management", "Leadership Development", "Managerial Skills Development", "Corporate Strategy Creation and Implementation", "Performance Management", "Strategic HRM"],
      biography: ["Coach and Consultant", "Strategic HR Management", "Impactful Leadership", "Creating and Implementing Corporate Strategy", "Senior Management Advisor"],
    },
    certification: {
      badge: "Recognised Speaker Credentials",
      heading: "Certification\non Successful\nCompletion",
      image: "/images/solutions/strategic-hr/certificate_image.jpg",
      paragraphs: [
        "When you complete the programme, you will receive a globally recognised certification from EIU Paris and the Global Association for Training & Development (GATD).",
        "This certification demonstrates your advanced expertise, commitment to professional excellence, and readiness to lead at the highest levels of your organisation.",
      ],
    },
    pillarHeading: "Programme Pillars",
    pillarBadge: "3 Days",
    pillarDays: [
      { label: "DAY 1", id: "day1" },
      { label: "DAY 2", id: "day2" },
      { label: "DAY 3", id: "day3" },
    ],
    pillarModules: {
      day1: [
        { id: 1, arrowTitle: "Strategic Resourcing Planning", labelPosition: "bottom", sideLabel: "Workforce Planning", sideDescription: "Aligning resourcing strategy with business direction to build the right capabilities at the right time" },
        { id: 2, arrowTitle: "Talent Attraction & Employer Brand", labelPosition: "top", sideLabel: "Employer Branding", sideDescription: "Building a compelling employer value proposition that attracts high-calibre talent in competitive markets" },
        { id: 3, arrowTitle: "Recruitment & Selection Excellence", labelPosition: "bottom", sideLabel: "Selection Systems", sideDescription: "Designing structured selection processes that identify the best talent and reduce bias in hiring decisions" },
        { id: 4, arrowTitle: "Onboarding & Integration", labelPosition: "top", sideLabel: "New Hire Success", sideDescription: "Creating onboarding experiences that accelerate time-to-performance and build early commitment" },
      ],
      day2: [
        { id: 1, arrowTitle: "Talent Identification & Assessment", labelPosition: "bottom", sideLabel: "Talent Analytics", sideDescription: "Using assessment tools and data to identify high-potential talent and build accurate capability profiles" },
        { id: 2, arrowTitle: "Succession Planning Frameworks", labelPosition: "top", sideLabel: "Pipeline Building", sideDescription: "Designing robust succession plans that ensure leadership continuity at every critical level" },
        { id: 3, arrowTitle: "Individual Development Planning", labelPosition: "bottom", sideLabel: "Growth Pathways", sideDescription: "Creating personalised development plans that accelerate capability growth and career progression" },
        { id: 4, arrowTitle: "Talent Review & Calibration", labelPosition: "top", sideLabel: "Talent Governance", sideDescription: "Running effective talent review processes that build consensus and drive meaningful development investment" },
      ],
      day3: [
        { id: 1, arrowTitle: "Learning Needs Analysis", labelPosition: "bottom", sideLabel: "L&D Strategy", sideDescription: "Identifying and prioritising capability gaps that require learning intervention to deliver business outcomes" },
        { id: 2, arrowTitle: "Learning Design & Delivery", labelPosition: "top", sideLabel: "Programme Design", sideDescription: "Designing blended learning experiences that engage learners and deliver measurable skill development" },
        { id: 3, arrowTitle: "Digital Learning & Technology", labelPosition: "bottom", sideLabel: "EdTech Integration", sideDescription: "Leveraging LMS platforms, e-learning, and emerging digital tools to scale learning across the organisation" },
        { id: 4, arrowTitle: "Learning Impact & ROI", labelPosition: "top", sideLabel: "L&D Measurement", sideDescription: "Measuring the effectiveness of learning programmes and demonstrating ROI to business stakeholders" },
      ],
    },
  },

  "hr-analytics": {
    parentSlug: "strategic-hr",
    parentTitle: "Strategic Human Resources, Business Leadership and Management",
    eyebrow: "Certified Programs",
    title: "Impactive HR for the Unitiated Certification",
    description: "This programme prepares HR professionals to harness data and digital tools to make evidence-based decisions, improve workforce planning, and lead HR transformation initiatives.",
    banner: "/images/solutions/strategic-hr/prog-1.jpg",
    subheading: "Lead HR in the Digital Age with Data-Driven Confidence",
    subtext: "Participants gain hands-on experience with HR analytics frameworks, digital HR tools, and transformation leadership — positioning HR as a data-driven strategic function.",
    focusHeading: "Focuses on Developing",
    focusAreas: [
      { id: 1, iconSrc: "/images/solutions/strategic-hr/1.svg", title: "HR Data Literacy & Metrics", description: "Building the data skills needed to collect, analyse, and present workforce insights confidently" },
      { id: 2, iconSrc: "/images/solutions/strategic-hr/2.svg", title: "People Analytics Strategy", description: "Building an enterprise analytics function with the right data, tools, and governance" },
      { id: 3, iconSrc: "/images/solutions/strategic-hr/3.svg", title: "Digital HR Ecosystem & AI", description: "Navigating HRIS, ATS, LMS, and AI-powered tools that are transforming HR delivery" },
      { id: 4, iconSrc: "/images/solutions/strategic-hr/4.svg", title: "HR Transformation Leadership", description: "Building and executing a digital HR transformation roadmap aligned with business strategy" },
      { id: 5, iconSrc: "/images/solutions/strategic-hr/5.svg", title: "Data Storytelling & Insight Communication", description: "Translating complex data into compelling narratives that influence business decisions" },
    ],
    faqs: [
      { id: 1, question: "Who is this programme for?", answer: "This programme is designed for HR professionals, managers, and senior leaders who want to build advanced expertise and drive meaningful business impact in their organisations." },
      { id: 2, question: "Is this certification recognised internationally?", answer: "Yes. This certification is accredited by EIU-Paris and GATD, recognised globally by leading organisations and professional bodies." },
      { id: 3, question: "Can I claim this under my corporate training budget?", answer: "Yes. Many participants claim this programme under their organisation's Learning & Development or corporate training budget. We can provide documentation to support your application." },
      { id: 4, question: "How long is the programme?", answer: "The programme runs over 3 intensive days, designed to maximise learning outcomes without a long absence from your role." },
      { id: 5, question: "I have a different question. Who should I contact?", answer: "Please contact us via email at ceo@globalatd.com or through our contact form and our team will respond within 24 hours." },
    ],
    facilitator: {
      name: "Prof. Dr. Joel Farnworth",
      role: "Dean of Business and Management Studies, EIU-Paris",
      image: "/images/solutions/strategic-hr/Dr_Joel.png",
      bg: "/images/solutions/strategic-hr/program_facilitator_BG.png",
      expertise: ["Human Resource Management", "Leadership Development", "Managerial Skills Development", "Corporate Strategy Creation and Implementation", "Performance Management", "Strategic HRM"],
      biography: ["Coach and Consultant", "Strategic HR Management", "Impactful Leadership", "Creating and Implementing Corporate Strategy", "Senior Management Advisor"],
    },
    certification: {
      badge: "Recognised Speaker Credentials",
      heading: "Certification\non Successful\nCompletion",
      image: "/images/solutions/strategic-hr/certificate_image.jpg",
      paragraphs: [
        "When you complete the programme, you will receive a globally recognised certification from EIU Paris and the Global Association for Training & Development (GATD).",
        "This certification demonstrates your advanced expertise, commitment to professional excellence, and readiness to lead at the highest levels of your organisation.",
      ],
    },
    pillarHeading: "Programme Pillars",
    pillarBadge: "3 Days",
    pillarDays: [
      { label: "DAY 1", id: "day1" },
      { label: "DAY 2", id: "day2" },
      { label: "DAY 3", id: "day3" },
    ],
    pillarModules: {
      day1: [
        { id: 1, arrowTitle: "HR Data Foundations", labelPosition: "bottom", sideLabel: "Data Literacy", sideDescription: "Building the data literacy skills HR professionals need to collect, clean, and interpret workforce data confidently" },
        { id: 2, arrowTitle: "HR Metrics & KPIs", labelPosition: "top", sideLabel: "HR Measurement", sideDescription: "Designing HR measurement frameworks and dashboards that demonstrate the value of people initiatives" },
        { id: 3, arrowTitle: "Workforce Analytics", labelPosition: "bottom", sideLabel: "Predictive Analytics", sideDescription: "Applying statistical and predictive analytics techniques to model workforce trends and inform strategic decisions" },
        { id: 4, arrowTitle: "People Analytics Strategy", labelPosition: "top", sideLabel: "Analytics Roadmap", sideDescription: "Building an enterprise people analytics function with the right data, tools, and governance structures" },
      ],
      day2: [
        { id: 1, arrowTitle: "Digital HR Ecosystem", labelPosition: "bottom", sideLabel: "HR Technology", sideDescription: "Mapping the digital HR technology landscape — HRIS, ATS, LMS, and emerging AI-powered tools" },
        { id: 2, arrowTitle: "HRIS Implementation & Optimisation", labelPosition: "top", sideLabel: "Systems Excellence", sideDescription: "Leading successful HRIS implementations and maximising the value of existing HR technology investments" },
        { id: 3, arrowTitle: "AI & Automation in HR", labelPosition: "bottom", sideLabel: "Future of HR Tech", sideDescription: "Exploring AI, machine learning, and automation applications that are transforming HR processes and decision-making" },
        { id: 4, arrowTitle: "Data Privacy & Ethics", labelPosition: "top", sideLabel: "Responsible Analytics", sideDescription: "Managing data governance, privacy regulations, and ethical considerations in people analytics programmes" },
      ],
      day3: [
        { id: 1, arrowTitle: "HR Transformation Strategy", labelPosition: "bottom", sideLabel: "Transformation Planning", sideDescription: "Building and executing an HR digital transformation roadmap aligned with business strategy and capability needs" },
        { id: 2, arrowTitle: "Change Management for HR Tech", labelPosition: "top", sideLabel: "Adoption Excellence", sideDescription: "Leading technology adoption with effective change management, training, and stakeholder engagement strategies" },
        { id: 3, arrowTitle: "Data Storytelling for HR", labelPosition: "bottom", sideLabel: "Insight Communication", sideDescription: "Translating complex data into compelling narratives and visualisations that influence business decisions" },
        { id: 4, arrowTitle: "Building the Digital HR Function", labelPosition: "top", sideLabel: "Future-Ready HR", sideDescription: "Designing the capabilities, operating model, and culture needed for a world-class digital HR function" },
      ],
    },
  },

  "employment-law": {
    parentSlug: "strategic-hr",
    parentTitle: "Strategic Human Resources, Business Leadership and Management",
    eyebrow: "Certified Programs",
    title: "Employment Law and Compliance",
    description: "This programme provides HR professionals with the legal knowledge and practical skills to navigate employment law, manage compliance risk, and protect both employees and the organisation.",
    banner: "/images/solutions/strategic-hr/prog-2.jpg",
    subheading: "Navigate Employment Law with Confidence and Clarity",
    subtext: "From contracts and disciplinary procedures to discrimination law and data protection, participants develop the legal literacy to advise confidently at all levels of the organisation.",
    focusHeading: "Focuses on Developing",
    focusAreas: [
      { id: 1, iconSrc: "/images/solutions/strategic-hr/1.svg", title: "Employment Contracts & Statutory Rights", description: "Understanding legal obligations in contracts, working time, pay, and employee entitlements" },
      { id: 2, iconSrc: "/images/solutions/strategic-hr/2.svg", title: "Discrimination & Equality Law", description: "Applying equality legislation across protected characteristics to build compliant workplaces" },
      { id: 3, iconSrc: "/images/solutions/strategic-hr/3.svg", title: "Disciplinary, Grievance & Absence", description: "Conducting legally compliant disciplinary, grievance, and absence management processes" },
      { id: 4, iconSrc: "/images/solutions/strategic-hr/4.svg", title: "Data Protection & Whistleblowing", description: "Applying GDPR in HR and building legally compliant whistleblowing frameworks" },
      { id: 5, iconSrc: "/images/solutions/strategic-hr/5.svg", title: "Tribunal Risk & HR Legal Partnership", description: "Minimising tribunal exposure and positioning HR as a trusted legal business partner" },
    ],
    faqs: [
      { id: 1, question: "Who is this programme for?", answer: "This programme is designed for HR professionals, managers, and senior leaders who want to build advanced expertise and drive meaningful business impact in their organisations." },
      { id: 2, question: "Is this certification recognised internationally?", answer: "Yes. This certification is accredited by EIU-Paris and GATD, recognised globally by leading organisations and professional bodies." },
      { id: 3, question: "Can I claim this under my corporate training budget?", answer: "Yes. Many participants claim this programme under their organisation's Learning & Development or corporate training budget. We can provide documentation to support your application." },
      { id: 4, question: "How long is the programme?", answer: "The programme runs over 3 intensive days, designed to maximise learning outcomes without a long absence from your role." },
      { id: 5, question: "I have a different question. Who should I contact?", answer: "Please contact us via email at ceo@globalatd.com or through our contact form and our team will respond within 24 hours." },
    ],
    facilitator: {
      name: "Prof. Dr. Joel Farnworth",
      role: "Dean of Business and Management Studies, EIU-Paris",
      image: "/images/solutions/strategic-hr/Dr_Joel.png",
      bg: "/images/solutions/strategic-hr/program_facilitator_BG.png",
      expertise: ["Human Resource Management", "Leadership Development", "Managerial Skills Development", "Corporate Strategy Creation and Implementation", "Performance Management", "Strategic HRM"],
      biography: ["Coach and Consultant", "Strategic HR Management", "Impactful Leadership", "Creating and Implementing Corporate Strategy", "Senior Management Advisor"],
    },
    certification: {
      badge: "Recognised Speaker Credentials",
      heading: "Certification\non Successful\nCompletion",
      image: "/images/solutions/strategic-hr/certificate_image.jpg",
      paragraphs: [
        "When you complete the programme, you will receive a globally recognised certification from EIU Paris and the Global Association for Training & Development (GATD).",
        "This certification demonstrates your advanced expertise, commitment to professional excellence, and readiness to lead at the highest levels of your organisation.",
      ],
    },
    pillarHeading: "Programme Pillars",
    pillarBadge: "3 Days",
    pillarDays: [
      { label: "DAY 1", id: "day1" },
      { label: "DAY 2", id: "day2" },
      { label: "DAY 3", id: "day3" },
    ],
    pillarModules: {
      day1: [
        { id: 1, arrowTitle: "Employment Contracts & Terms", labelPosition: "bottom", sideLabel: "Contractual Foundations", sideDescription: "Understanding the legal requirements and best practices for drafting, managing, and varying employment contracts" },
        { id: 2, arrowTitle: "Recruitment & Pre-Employment Law", labelPosition: "top", sideLabel: "Hiring Compliance", sideDescription: "Navigating legal obligations during recruitment — from job advertising through to offer and onboarding" },
        { id: 3, arrowTitle: "Working Time & Pay Legislation", labelPosition: "bottom", sideLabel: "Pay & Hours Compliance", sideDescription: "Applying working time regulations, minimum wage law, and pay transparency requirements correctly and confidently" },
        { id: 4, arrowTitle: "Employee Rights & Obligations", labelPosition: "top", sideLabel: "Statutory Rights", sideDescription: "Understanding the full spectrum of statutory employee rights and the employer obligations that accompany them" },
      ],
      day2: [
        { id: 1, arrowTitle: "Discrimination & Equality Law", labelPosition: "bottom", sideLabel: "Equality Compliance", sideDescription: "Applying discrimination law across all protected characteristics and building workplace equality frameworks" },
        { id: 2, arrowTitle: "Disciplinary & Grievance Procedures", labelPosition: "top", sideLabel: "Process Management", sideDescription: "Designing and conducting legally compliant disciplinary and grievance processes that protect all parties" },
        { id: 3, arrowTitle: "Absence & Health Management", labelPosition: "bottom", sideLabel: "Absence Compliance", sideDescription: "Managing short and long-term absence legally — including fit notes, reasonable adjustments, and capability procedures" },
        { id: 4, arrowTitle: "Termination & Redundancy Law", labelPosition: "top", sideLabel: "Exit Compliance", sideDescription: "Navigating dismissal, redundancy, and settlement agreements in compliance with employment law obligations" },
      ],
      day3: [
        { id: 1, arrowTitle: "Data Protection & GDPR in HR", labelPosition: "bottom", sideLabel: "Data Compliance", sideDescription: "Applying GDPR and data protection law to HR processes — from data collection through to subject access requests" },
        { id: 2, arrowTitle: "Whistleblowing & Protected Disclosure", labelPosition: "top", sideLabel: "Whistleblowing Law", sideDescription: "Building legally compliant whistleblowing frameworks that protect disclosers and manage organisational risk" },
        { id: 3, arrowTitle: "Employment Tribunal Risk Management", labelPosition: "bottom", sideLabel: "Tribunal Preparedness", sideDescription: "Minimising employment tribunal risk through proactive compliance, documentation, and early dispute resolution" },
        { id: 4, arrowTitle: "HR as Legal Business Partner", labelPosition: "top", sideLabel: "Strategic HR Law", sideDescription: "Positioning HR as a trusted legal advisor that proactively manages compliance risk and supports business decisions" },
      ],
    },
  },

  "org-design-change": {
    parentSlug: "strategic-hr",
    parentTitle: "Strategic Human Resources, Business Leadership and Management",
    eyebrow: "Certified Programs",
    title: "Organisational Design and Change",
    description: "This programme equips HR and change leaders with the methodologies to design effective organisations, lead structural transformation, and embed sustainable change across the enterprise.",
    banner: "/images/solutions/strategic-hr/prog-3.jpg",
    subheading: "Design Organisations That Are Built to Perform and Adapt",
    subtext: "Participants learn proven frameworks for organisational design, change management, and culture transformation — enabling them to lead complex change with stakeholder buy-in and lasting results.",
    focusHeading: "Focuses on Developing",
    focusAreas: [
      { id: 1, iconSrc: "/images/solutions/strategic-hr/1.svg", title: "Organisational Design & Operating Models", description: "Designing effective org structures and target operating models aligned to business strategy" },
      { id: 2, iconSrc: "/images/solutions/strategic-hr/2.svg", title: "Change Management Frameworks", description: "Applying proven change models — Kotter, ADKAR, McKinsey 7S — to lead transformation" },
      { id: 3, iconSrc: "/images/solutions/strategic-hr/3.svg", title: "Stakeholder Engagement & Communication", description: "Securing buy-in and maintaining alignment through structured stakeholder engagement plans" },
      { id: 4, iconSrc: "/images/solutions/strategic-hr/4.svg", title: "Culture Assessment & Transformation", description: "Measuring current culture and designing the target culture needed to sustain performance" },
      { id: 5, iconSrc: "/images/solutions/strategic-hr/5.svg", title: "Sustaining Change & Building Resilience", description: "Embedding governance structures and adaptive capabilities that sustain transformation outcomes" },
    ],
    faqs: [
      { id: 1, question: "Who is this programme for?", answer: "This programme is designed for HR professionals, managers, and senior leaders who want to build advanced expertise and drive meaningful business impact in their organisations." },
      { id: 2, question: "Is this certification recognised internationally?", answer: "Yes. This certification is accredited by EIU-Paris and GATD, recognised globally by leading organisations and professional bodies." },
      { id: 3, question: "Can I claim this under my corporate training budget?", answer: "Yes. Many participants claim this programme under their organisation's Learning & Development or corporate training budget. We can provide documentation to support your application." },
      { id: 4, question: "How long is the programme?", answer: "The programme runs over 3 intensive days, designed to maximise learning outcomes without a long absence from your role." },
      { id: 5, question: "I have a different question. Who should I contact?", answer: "Please contact us via email at ceo@globalatd.com or through our contact form and our team will respond within 24 hours." },
    ],
    facilitator: {
      name: "Prof. Dr. Joel Farnworth",
      role: "Dean of Business and Management Studies, EIU-Paris",
      image: "/images/solutions/strategic-hr/Dr_Joel.png",
      bg: "/images/solutions/strategic-hr/program_facilitator_BG.png",
      expertise: ["Human Resource Management", "Leadership Development", "Managerial Skills Development", "Corporate Strategy Creation and Implementation", "Performance Management", "Strategic HRM"],
      biography: ["Coach and Consultant", "Strategic HR Management", "Impactful Leadership", "Creating and Implementing Corporate Strategy", "Senior Management Advisor"],
    },
    certification: {
      badge: "Recognised Speaker Credentials",
      heading: "Certification\non Successful\nCompletion",
      image: "/images/solutions/strategic-hr/certificate_image.jpg",
      paragraphs: [
        "When you complete the programme, you will receive a globally recognised certification from EIU Paris and the Global Association for Training & Development (GATD).",
        "This certification demonstrates your advanced expertise, commitment to professional excellence, and readiness to lead at the highest levels of your organisation.",
      ],
    },
    pillarHeading: "Programme Pillars",
    pillarBadge: "3 Days",
    pillarDays: [
      { label: "DAY 1", id: "day1" },
      { label: "DAY 2", id: "day2" },
      { label: "DAY 3", id: "day3" },
    ],
    pillarModules: {
      day1: [
        { id: 1, arrowTitle: "Organisational Design Principles", labelPosition: "bottom", sideLabel: "OD Foundations", sideDescription: "Understanding the core principles and models of organisational design — structure, processes, people, and culture" },
        { id: 2, arrowTitle: "Operating Model Design", labelPosition: "top", sideLabel: "Operating Models", sideDescription: "Designing target operating models that align organisational structure with business strategy and customer needs" },
        { id: 3, arrowTitle: "Role & Capability Architecture", labelPosition: "bottom", sideLabel: "Role Design", sideDescription: "Building role frameworks and capability architectures that support the target operating model" },
        { id: 4, arrowTitle: "Organisational Diagnostics", labelPosition: "top", sideLabel: "OD Assessment", sideDescription: "Conducting organisational assessments to identify design gaps, inefficiencies, and transformation priorities" },
      ],
      day2: [
        { id: 1, arrowTitle: "Change Management Frameworks", labelPosition: "bottom", sideLabel: "Change Models", sideDescription: "Applying globally recognised change models including Kotter, ADKAR, and McKinsey 7S to lead transformation" },
        { id: 2, arrowTitle: "Stakeholder Engagement Strategy", labelPosition: "top", sideLabel: "Stakeholder Management", sideDescription: "Building stakeholder maps and engagement plans that secure buy-in and reduce resistance to change" },
        { id: 3, arrowTitle: "Change Communication Planning", labelPosition: "bottom", sideLabel: "Change Communication", sideDescription: "Designing multi-channel communication plans that maintain trust and alignment throughout transformation" },
        { id: 4, arrowTitle: "Managing Resistance & Transition", labelPosition: "top", sideLabel: "Transition Management", sideDescription: "Diagnosing resistance patterns and applying evidence-based techniques to guide people through transition" },
      ],
      day3: [
        { id: 1, arrowTitle: "Culture Assessment & Design", labelPosition: "bottom", sideLabel: "Culture Strategy", sideDescription: "Measuring current culture and designing the target culture needed to support transformation and performance" },
        { id: 2, arrowTitle: "Culture Embedding Strategies", labelPosition: "top", sideLabel: "Culture Activation", sideDescription: "Using leadership behaviour, rituals, symbols, and stories to embed and sustain cultural transformation" },
        { id: 3, arrowTitle: "Sustaining Change & Governance", labelPosition: "bottom", sideLabel: "Change Governance", sideDescription: "Building governance structures and measurement systems that sustain change outcomes beyond implementation" },
        { id: 4, arrowTitle: "Leading Future-Ready Organisations", labelPosition: "top", sideLabel: "Adaptive Organisations", sideDescription: "Building the adaptive, agile organisational capabilities needed to continuously evolve in a changing environment" },
      ],
    },
  },

  "compensation-benefits": {
    parentSlug: "strategic-hr",
    parentTitle: "Strategic Human Resources, Business Leadership and Management",
    eyebrow: "Certified Programs",
    title: "Executive Compensation and Benefits Strategy",
    description: "This advanced programme covers the design and governance of executive compensation and benefits packages — equipping HR leaders to develop competitive, compliant, and strategically aligned reward frameworks.",
    banner: "/images/solutions/strategic-hr/prog-4.jpg",
    subheading: "Design Executive Reward Strategies That Attract and Retain Top Leaders",
    subtext: "Participants gain expertise in executive pay structures, benefits benchmarking, board reporting, and the governance frameworks that ensure fairness, transparency, and regulatory compliance.",
    focusHeading: "Focuses on Developing",
    focusAreas: [
      { id: 1, iconSrc: "/images/solutions/strategic-hr/1.svg", title: "Executive Pay Architecture & LTIs", description: "Designing base salary, short-term incentives, and long-term equity schemes for senior leaders" },
      { id: 2, iconSrc: "/images/solutions/strategic-hr/2.svg", title: "Market Benchmarking & Pay Positioning", description: "Using executive pay surveys to build competitive and equitable compensation structures" },
      { id: 3, iconSrc: "/images/solutions/strategic-hr/3.svg", title: "Executive Benefits & Tax Efficiency", description: "Structuring pensions, benefits, and perquisites for both value and tax optimisation" },
      { id: 4, iconSrc: "/images/solutions/strategic-hr/4.svg", title: "Remuneration Committee Governance", description: "Understanding board governance frameworks and regulatory reporting on executive pay" },
      { id: 5, iconSrc: "/images/solutions/strategic-hr/5.svg", title: "Shareholder Engagement & Future Trends", description: "Managing investor engagement on pay and exploring ESG-linked executive reward innovations" },
    ],
    faqs: [
      { id: 1, question: "Who is this programme for?", answer: "This programme is designed for HR professionals, managers, and senior leaders who want to build advanced expertise and drive meaningful business impact in their organisations." },
      { id: 2, question: "Is this certification recognised internationally?", answer: "Yes. This certification is accredited by EIU-Paris and GATD, recognised globally by leading organisations and professional bodies." },
      { id: 3, question: "Can I claim this under my corporate training budget?", answer: "Yes. Many participants claim this programme under their organisation's Learning & Development or corporate training budget. We can provide documentation to support your application." },
      { id: 4, question: "How long is the programme?", answer: "The programme runs over 3 intensive days, designed to maximise learning outcomes without a long absence from your role." },
      { id: 5, question: "I have a different question. Who should I contact?", answer: "Please contact us via email at ceo@globalatd.com or through our contact form and our team will respond within 24 hours." },
    ],
    facilitator: {
      name: "Prof. Dr. Joel Farnworth",
      role: "Dean of Business and Management Studies, EIU-Paris",
      image: "/images/solutions/strategic-hr/Dr_Joel.png",
      bg: "/images/solutions/strategic-hr/program_facilitator_BG.png",
      expertise: ["Human Resource Management", "Leadership Development", "Managerial Skills Development", "Corporate Strategy Creation and Implementation", "Performance Management", "Strategic HRM"],
      biography: ["Coach and Consultant", "Strategic HR Management", "Impactful Leadership", "Creating and Implementing Corporate Strategy", "Senior Management Advisor"],
    },
    certification: {
      badge: "Recognised Speaker Credentials",
      heading: "Certification\non Successful\nCompletion",
      image: "/images/solutions/strategic-hr/certificate_image.jpg",
      paragraphs: [
        "When you complete the programme, you will receive a globally recognised certification from EIU Paris and the Global Association for Training & Development (GATD).",
        "This certification demonstrates your advanced expertise, commitment to professional excellence, and readiness to lead at the highest levels of your organisation.",
      ],
    },
    pillarHeading: "Programme Pillars",
    pillarBadge: "3 Days",
    pillarDays: [
      { label: "DAY 1", id: "day1" },
      { label: "DAY 2", id: "day2" },
      { label: "DAY 3", id: "day3" },
    ],
    pillarModules: {
      day1: [
        { id: 1, arrowTitle: "Executive Pay Architecture", labelPosition: "bottom", sideLabel: "Pay Structure Design", sideDescription: "Designing executive pay structures — base salary, short-term incentives, and total cash frameworks" },
        { id: 2, arrowTitle: "Long-Term Incentive Plans", labelPosition: "top", sideLabel: "LTI Design", sideDescription: "Structuring equity, share, and long-term incentive schemes that align executive interests with shareholder value" },
        { id: 3, arrowTitle: "Market Benchmarking & Pay Positioning", labelPosition: "bottom", sideLabel: "Competitive Analysis", sideDescription: "Using executive pay surveys and benchmarking methodologies to position compensation competitively" },
        { id: 4, arrowTitle: "Pay-for-Performance Linkage", labelPosition: "top", sideLabel: "Performance Alignment", sideDescription: "Designing performance conditions and metrics that create clear line-of-sight between pay and business outcomes" },
      ],
      day2: [
        { id: 1, arrowTitle: "Executive Benefits Strategy", labelPosition: "bottom", sideLabel: "Benefits Design", sideDescription: "Designing comprehensive executive benefits packages — pensions, healthcare, perquisites, and protection benefits" },
        { id: 2, arrowTitle: "Pension & Retirement Governance", labelPosition: "top", sideLabel: "Retirement Planning", sideDescription: "Managing executive pension arrangements, defined contribution schemes, and alternative retirement provisions" },
        { id: 3, arrowTitle: "Tax Efficiency in Executive Reward", labelPosition: "bottom", sideLabel: "Tax Optimisation", sideDescription: "Structuring executive reward packages for tax efficiency while maintaining compliance and fairness" },
        { id: 4, arrowTitle: "International Executive Mobility", labelPosition: "top", sideLabel: "Global Reward", sideDescription: "Managing executive reward for internationally mobile leaders — expatriate packages, tax equalisation, and secondments" },
      ],
      day3: [
        { id: 1, arrowTitle: "Remuneration Committee Governance", labelPosition: "bottom", sideLabel: "Board Governance", sideDescription: "Understanding remuneration committee structures, responsibilities, and the governance principles that guide executive pay decisions" },
        { id: 2, arrowTitle: "Executive Pay Reporting", labelPosition: "top", sideLabel: "Pay Transparency", sideDescription: "Meeting regulatory reporting requirements and communicating executive pay decisions clearly to shareholders" },
        { id: 3, arrowTitle: "Shareholder Engagement on Pay", labelPosition: "bottom", sideLabel: "Investor Relations", sideDescription: "Managing institutional shareholder engagement on executive compensation and responding to advisory votes" },
        { id: 4, arrowTitle: "Future Trends in Executive Reward", labelPosition: "top", sideLabel: "Reward Innovation", sideDescription: "Exploring ESG-linked pay, purpose-driven incentives, and the evolving landscape of executive reward practices" },
      ],
    },
  },
};
