export const solutionsData = {
  // ── Executive Educational ──────────────────────────────────────────────────
  "spldp": {
    eyebrow: "Executive Educational Program",
    title: "Singapore Potential Leadership Development Program (SPLDP)",
    description: "The SPLDP is designed to develop high-potential leaders in Singapore, equipping them with the strategic insight, executive presence, and cross-functional capabilities needed to lead at the highest levels.",
    banner: "/images/solutions/executive-educational/Singapore-Potential.jpg",
    subheading: "Develop Singapore's Next Generation of Strategic Leaders",
    subtext: "This flagship program blends immersive learning, peer collaboration, and expert mentorship to cultivate leaders who are ready to navigate complexity and drive transformation across sectors.",
  },
  "women-in-leadership": {
    eyebrow: "Executive Educational Program",
    title: "Women in Leadership",
    description: "This program empowers women professionals to take on senior leadership roles with confidence, strategic clarity, and a global perspective. It combines executive coaching, peer learning, and real-world application.",
    banner: "/images/solutions/executive-educational/Women-in-Leadership.jpg",
    subheading: "Empowering Women to Lead at Every Level",
    subtext: "Through a combination of evidence-based frameworks and transformative experiences, this program prepares women leaders to overcome barriers and excel in executive roles.",
  },
  "next-gen-cxo": {
    eyebrow: "Executive Educational Program",
    title: "Next-Gen Strategic Leadership for CxOs",
    description: "Designed for aspiring and current C-suite executives, this program sharpens strategic thinking, digital fluency, and enterprise leadership capabilities needed in today's fast-moving environment.",
    banner: "/images/solutions/executive-educational/Next-Gen-Strategic-Leadership.jpg",
    subheading: "Shape the Next Generation of Executive Leaders",
    subtext: "Participants gain the tools, networks, and mindset to lead digital transformation, drive innovation, and build resilient organisations.",
  },
  "ceo-mastery": {
    eyebrow: "Executive Educational Program",
    title: "Global CEO Executive Leadership Mastery Program",
    description: "A world-class program crafted for CEOs and senior executives, blending global best practices with practical leadership mastery to drive organisational excellence and lasting impact.",
    banner: "/images/solutions/executive-educational/Global-CEO-Executive-Leadership-Mastery.jpg",
    subheading: "Master the Art and Science of CEO Leadership",
    subtext: "This program draws on global case studies, executive peer forums, and personalised coaching to elevate your leadership impact at the very top of the organisation.",
  },

  // ── Consulting ─────────────────────────────────────────────────────────────
  "ministries": {
    eyebrow: "Consulting Service",
    title: "Ministries Regional & International",
    description: "GATD partners with government ministries to design and deliver leadership and capacity-building programmes that align with national development agendas, both regionally and internationally.",
    banner: "/images/solutions/consulting-1.jpg",
    subheading: "Building Government Leadership Capacity for National Growth",
    subtext: "Our bespoke ministry programmes are co-created with stakeholders to ensure relevance, impact, and sustainable capability development across public sector institutions.",
  },
  "talent-development": {
    eyebrow: "Consulting Service",
    title: "Talent Development & Succession Planning",
    description: "We help organisations identify, develop, and retain top talent while building robust succession pipelines to ensure leadership continuity and organisational resilience.",
    banner: "/images/solutions/consulting-2.jpg",
    subheading: "Secure Your Organisation's Leadership Future",
    subtext: "Our systematic approach to talent development links individual growth with business strategy, ensuring the right leaders are ready at the right time.",
  },
  "workforce-planning": {
    eyebrow: "Consulting Service",
    title: "Strategic Workforce Planning and Development",
    description: "GATD provides data-driven workforce planning frameworks that align human capital with future business needs, helping organisations build agile, future-ready teams.",
    banner: "/images/solutions/consulting-3.jpg",
    subheading: "Align Your People Strategy with Business Direction",
    subtext: "We work alongside HR and business leaders to model workforce scenarios, close capability gaps, and build sustainable talent pipelines.",
  },
  "balanced-scorecard": {
    eyebrow: "Consulting Service",
    title: "Balanced Scorecard & Performance Management",
    description: "Our consultants help organisations implement the Balanced Scorecard framework to translate strategy into measurable objectives, driving accountability and performance at every level.",
    banner: "/images/solutions/consulting-4.jpg",
    subheading: "Turn Strategy into Measurable Results",
    subtext: "We guide leadership teams through the design, implementation, and embedding of performance management systems that connect individual KPIs to organisational goals.",
  },

  // ── Customized Programs ────────────────────────────────────────────────────
  "risk-crisis": {
    eyebrow: "Customized Programs",
    title: "Risk & Crisis Management Leadership",
    description: "This programme equips leaders with the frameworks, tools, and decision-making skills to navigate risk and lead effectively through crises — protecting people, reputation, and business continuity.",
    banner: "/images/solutions/custom-1.jpg",
    subheading: "Lead with Confidence When It Matters Most",
    subtext: "Combining simulation-based learning with expert facilitation, participants develop the resilience and agility to respond decisively under pressure.",
  },
  "strategic-rightsizing": {
    eyebrow: "Customized Programs",
    title: "Strategic Rightsizing",
    description: "GATD supports organisations in rightsizing their workforce in a way that preserves productivity, culture, and morale — ensuring sustainable operations aligned with strategic priorities.",
    banner: "/images/solutions/custom-2.jpg",
    subheading: "Restructure Thoughtfully, Lead Effectively",
    subtext: "Our methodology balances financial imperatives with people-centred leadership, guiding organisations through transitions that maintain trust and engagement.",
  },
  "mergers-acquisitions": {
    eyebrow: "Customized Programs",
    title: "Transformation Leadership in Mergers & Acquisitions",
    description: "We prepare leadership teams to navigate the human and strategic complexities of M&A — from cultural integration to change communication and performance continuity.",
    banner: "/images/solutions/custom-3.jpg",
    subheading: "Lead Successful Transformations Through Mergers & Acquisitions",
    subtext: "GATD's M&A leadership programme helps executives and managers drive integration effectively, reduce disruption, and unlock the full value of strategic transactions.",
  },
  "goie": {
    eyebrow: "Customized Programs",
    title: "Global Operations in Excellence (GOiE)",
    description: "GOiE is a comprehensive programme designed to elevate operational performance across global organisations, embedding excellence principles into culture, processes, and leadership practice.",
    banner: "/images/solutions/custom-4.jpg",
    subheading: "Embed Operational Excellence Across Your Global Enterprise",
    subtext: "Participants learn proven methodologies and global best practices that drive efficiency, quality, and continuous improvement at scale.",
  },

  // ── Certified Programs ─────────────────────────────────────────────────────
  "strategic-hr": {
    eyebrow: "Certified Programs",
    title: "Strategic Human Resources, Business Leadership and Management",
    description: "This suite offers eight executive-level certifications that help specialists become strategic leaders. You will learn how to improve performance, leadership, and human capital to achieve real business results. All programs are accredited by EIU-Paris.",
    banner: "/images/solutions/strategic-hr/banner.jpg",
    subheading: "Advance Your Expertise in Strategic HR and Management with Global ATD",
    subtext: "The Strategic Human Resources, Business Leadership and Management Certifications Program helps professionals connect people, performance, and business strategy for greater impact. Its specialised courses build advanced skills in leadership, talent development, and HR effectiveness. The program prepares HR leaders to drive growth and add real value.",
    mapImage: "/images/solutions/strategic-hr/map.jpg",
    gainsHeading: "What You'll Gain From This Certification Suite",
    whyHeading: "Why this Suite is Worth the Investment",
    whyBadge: "Invest in building results that last",
    whyImage: "/images/solutions/strategic-hr/plan.jpg",
    audienceBadge: "Who is This",
    audienceHeading: "Programme Suite Designed For?",
    audienceImage: "/images/solutions/strategic-hr/programme-suits.jpg",
    audience: [
      "Senior HR Leaders & Directors",
      "Aspiring C-Suite & High-Potentials",
      "Business Unit Heads & GMs",
      "L&D Specialists",
      "Executive Consultants & Advisors",
    ],
    gains: [
      { id: 1, iconSrc: "/images/solutions/strategic-hr/icon-1.svg", text: "Develop deep expertise in all key areas of human resources and management across modern business environments" },
      { id: 2, iconSrc: "/images/solutions/strategic-hr/icon-2.svg", text: "Earn EIU-Paris and GATD accreditation, recognized worldwide, and connect with top-tier professional network" },
      { id: 3, iconSrc: "/images/solutions/strategic-hr/icon-3.svg", text: "Learn practical frameworks & strategies to help you turn your team's talent into real business growth you can measure" },
      { id: 4, iconSrc: "/images/solutions/strategic-hr/icon-4.svg", text: "Build the leadership skills you need to succeed confidently in the modern executive boardroom environment" },
      { id: 5, iconSrc: "/images/solutions/strategic-hr/icon-5.svg", text: "Apply advanced tools to help your team work more efficiently and deliver consistently high-performance results" },
    ],
    programmes: [
      { id: 1, title: "Strategic HR Business Partnership and Beyond", image: "/images/solutions/strategic-hr/prog-1.jpg", href: "/solutions/strategic-hr/strategic-hr-business-partnership" },
      { id: 2, title: "Impactful Business and People Leadership", image: "/images/solutions/strategic-hr/prog-2.jpg", href: "/solutions/strategic-hr/business-people-leadership" },
      { id: 3, title: "Performance Development and Rewards Management", image: "/images/solutions/strategic-hr/prog-3.jpg", href: "/solutions/strategic-hr/performance-rewards" },
      { id: 4, title: "Resourcing, Talent and Learning Management", image: "/images/solutions/strategic-hr/prog-4.jpg", href: "/solutions/strategic-hr/resourcing-talent-learning" },
      { id: 5, title: "HR Analytics and Digital Transformation", image: "/images/solutions/strategic-hr/prog-1.jpg", href: "/solutions/strategic-hr/hr-analytics" },
      { id: 6, title: "Employment Law and Compliance", image: "/images/solutions/strategic-hr/prog-2.jpg", href: "/solutions/strategic-hr/employment-law" },
      { id: 7, title: "Organisational Design and Change", image: "/images/solutions/strategic-hr/prog-3.jpg", href: "/solutions/strategic-hr/org-design-change" },
      { id: 8, title: "Executive Compensation and Benefits Strategy", image: "/images/solutions/strategic-hr/prog-4.jpg", href: "/solutions/strategic-hr/compensation-benefits" },
    ],
  },
  "change-management": {
    eyebrow: "Certified Programs",
    title: "Change Management",
    description: "This certification equips practitioners with the methodologies, tools, and leadership skills to plan, implement, and sustain organisational change effectively.",
    banner: "/images/solutions/certified-2.jpg",
    subheading: "Lead Change with Confidence and Competence",
    subtext: "GATD's Change Management certification programme is grounded in globally recognised frameworks, preparing you to guide people and organisations through complex transitions.",
  },
  "ppp": {
    eyebrow: "Certified Programs",
    title: "Public Private Partnerships",
    description: "This programme builds the expertise required to structure, negotiate, and manage successful PPP arrangements — bridging public sector goals with private sector capabilities.",
    banner: "/images/solutions/certified-3.jpg",
    subheading: "Master the Complexity of Public Private Partnerships",
    subtext: "Participants gain practical knowledge of PPP frameworks, financial structuring, risk allocation, and stakeholder management to deliver sustainable infrastructure and services.",
  },
  "kpis": {
    eyebrow: "Certified Programs",
    title: "Key Performance Indicators (KPIs)",
    description: "Learn to design, implement, and manage KPI systems that drive organisational accountability and align daily activity with strategic objectives.",
    banner: "/images/solutions/certified-4.jpg",
    subheading: "Build a Performance Culture with Meaningful KPIs",
    subtext: "This certification covers KPI design principles, data collection, dashboarding, and the leadership behaviours that turn metrics into sustained performance improvements.",
  },

  // ── Executive Retreats ─────────────────────────────────────────────────────
  "strategic-reset": {
    eyebrow: "Executive Retreats",
    title: "Strategic Reset Retreat",
    description: "A transformative leadership retreat designed to help executive teams step back, reflect on strategy, and realign on shared goals — in an environment that inspires bold thinking.",
    banner: "/images/solutions/retreat-1.jpg",
    subheading: "Recharge, Realign, and Rethink Your Strategy",
    subtext: "Facilitated by GATD's expert coaches, this immersive retreat blends strategic workshops, outdoor activities, and reflective sessions to energise your leadership team.",
  },
  "gatsby-gala": {
    eyebrow: "Executive Retreats",
    title: "The Great Gatsby Gala",
    description: "An elegant, themed executive experience that combines high-energy networking, celebration, and leadership inspiration in a memorable Gatsby-style setting.",
    banner: "/images/solutions/retreat-2.jpg",
    subheading: "Celebrate Excellence in Style",
    subtext: "The Great Gatsby Gala is GATD's signature evening retreat event — a bespoke experience curated to reward achievement, foster connection, and inspire continued ambition.",
  },
  "all-star-carnival": {
    eyebrow: "Executive Retreats",
    title: "The All-Star Carnival",
    description: "A vibrant, fun-filled team retreat experience that blends competition, creativity, and collaboration — designed to energise teams and celebrate collective achievement.",
    banner: "/images/solutions/retreat-3.jpg",
    subheading: "Unleash Your Team's Energy and Spirit",
    subtext: "The All-Star Carnival brings teams together through immersive activities, friendly competition, and shared celebration — building bonds that carry back into the workplace.",
  },

  // ── Incubators ─────────────────────────────────────────────────────────────
  "global-healthtech": {
    eyebrow: "Incubators — Regional & International",
    title: "Global HealthTech",
    description: "GATD's Global HealthTech Incubator connects health-focused innovators with global networks, mentorship, and funding pathways to accelerate the development of transformative health technologies.",
    banner: "/images/solutions/incubator-1.jpg",
    subheading: "Accelerate Health Innovation on a Global Scale",
    subtext: "Our HealthTech programme supports startups and enterprises developing impactful solutions at the intersection of healthcare and technology.",
  },
  "net-zero": {
    eyebrow: "Incubators — Regional & International",
    title: "Net Zero Innovation Lab",
    description: "A dedicated incubator for clean-tech and sustainability innovators, helping organisations develop, test, and scale solutions that accelerate the transition to net zero.",
    banner: "/images/solutions/incubator-2.jpg",
    subheading: "Build Solutions for a Sustainable Future",
    subtext: "GATD's Net Zero Innovation Lab provides the expertise, networks, and support to help innovators translate sustainable ideas into market-ready solutions.",
  },
  "govtech": {
    eyebrow: "Incubators — Regional & International",
    title: "GovTech Catalyst Hub",
    description: "The GovTech Catalyst Hub accelerates the development of technology solutions that improve public services, government efficiency, and citizen outcomes.",
    banner: "/images/solutions/incubator-3.jpg",
    subheading: "Transform Public Services Through Technology Innovation",
    subtext: "We connect GovTech innovators with government partners, facilitating co-creation and rapid deployment of digital solutions that deliver real public value.",
  },
  "edtech": {
    eyebrow: "Incubators — Regional & International",
    title: "EdTech Skills",
    description: "The EdTech Skills Incubator supports innovators building the next generation of learning technologies — tools that make education more accessible, engaging, and effective.",
    banner: "/images/solutions/incubator-4.jpg",
    subheading: "Shape the Future of Learning Through EdTech",
    subtext: "From AI-powered platforms to immersive learning experiences, our EdTech programme helps innovators bring transformative solutions to learners worldwide.",
  },

  // ── Event Management ───────────────────────────────────────────────────────
  "program-management": {
    eyebrow: "Event Management",
    title: "Program Management",
    description: "GATD delivers end-to-end programme management for complex, multi-stakeholder events — ensuring every detail is executed with precision, professionalism, and purpose.",
    banner: "/images/solutions/event-1.jpg",
    subheading: "Flawless Execution for High-Stakes Programmes",
    subtext: "Our experienced programme management team handles planning, logistics, stakeholder coordination, and on-site delivery so you can focus on the impact.",
  },
  "csr-events": {
    eyebrow: "Event Management",
    title: "Corporate Social Responsibility (CSR) Events",
    description: "We design and manage meaningful CSR events that connect your organisation with communities, amplify your social impact, and build brand reputation through authentic engagement.",
    banner: "/images/solutions/event-2.jpg",
    subheading: "Create Social Impact Through Purpose-Driven Events",
    subtext: "From community initiatives to charity partnerships, GATD brings creativity, logistics excellence, and purpose to every CSR event we manage.",
  },
  "product-launches": {
    eyebrow: "Event Management",
    title: "Product Launches & Brand Activation Events",
    description: "We create high-impact product launch experiences and brand activation events that generate excitement, media attention, and lasting audience engagement.",
    banner: "/images/solutions/event-3.jpg",
    subheading: "Launch Boldly. Activate Powerfully.",
    subtext: "GATD's event specialists craft immersive launch experiences that bring your brand story to life and leave audiences inspired to act.",
  },
  "trade-shows": {
    eyebrow: "Event Management",
    title: "Trade Shows and Expo Management",
    description: "From booth design to full expo logistics, GATD manages every aspect of trade show participation to maximise your ROI and brand visibility.",
    banner: "/images/solutions/event-4.jpg",
    subheading: "Stand Out on the Global Trade Show Stage",
    subtext: "Our trade show specialists handle everything from pre-show strategy to on-floor execution and post-event follow-up, ensuring your presence makes a lasting impression.",
  },

  // ── Global Conferences ─────────────────────────────────────────────────────
  "global-marketing-forum": {
    eyebrow: "Global Conferences",
    title: "Global Marketing Forum",
    description: "A premier conference bringing together marketing leaders from around the world to explore the latest trends, innovations, and strategies shaping the future of global marketing.",
    banner: "/images/solutions/conference-1.jpg",
    subheading: "Where Global Marketing Leaders Connect and Collaborate",
    subtext: "The Global Marketing Forum features keynote speakers, panel discussions, and networking sessions that help marketers stay ahead of the curve in a rapidly evolving landscape.",
  },
  "energy-governance": {
    eyebrow: "Global Conferences",
    title: "Energy Governance & Leadership Summit",
    description: "A high-level summit for energy sector leaders, policymakers, and innovators to explore governance frameworks, leadership practices, and the strategic direction of global energy.",
    banner: "/images/solutions/conference-2.jpg",
    subheading: "Shaping the Future of Energy Leadership and Governance",
    subtext: "This summit brings together decision-makers to forge the policies, partnerships, and strategies that will drive the global energy transition.",
  },
  "zero-summit": {
    eyebrow: "Global Conferences",
    title: "The Zero Summit: Strategic Dialogues for a Net Zero World",
    description: "A landmark conference dedicated to accelerating the net zero transition through strategic dialogue, knowledge exchange, and commitment-making among global leaders.",
    banner: "/images/solutions/conference-3.jpg",
    subheading: "Accelerate the Path to Net Zero Through Strategic Dialogue",
    subtext: "The Zero Summit convenes governments, businesses, and civil society to drive ambitious, collaborative action on climate and sustainability.",
  },
  "petroforesight": {
    eyebrow: "Global Conferences",
    title: "PetroForesight 2030: The Leadership Blueprint for Energy Transition",
    description: "PetroForesight 2030 is a forward-looking energy conference that equips oil, gas, and energy leaders with the strategic blueprint for navigating the energy transition to 2030 and beyond.",
    banner: "/images/solutions/conference-4.jpg",
    subheading: "Navigate the Energy Transition with Strategic Foresight",
    subtext: "From decarbonisation strategies to new energy business models, PetroForesight 2030 provides the insights and connections energy leaders need to thrive in a transforming industry.",
  },

  // ── Industry Specific ──────────────────────────────────────────────────────
  "financial-strategy": {
    eyebrow: "Industry Specific",
    title: "Advanced Program in Financial Strategy for Executives",
    description: "This executive programme provides senior leaders with advanced financial strategy skills — from capital allocation and M&A to value creation and investor relations.",
    banner: "/images/solutions/industry-1.jpg",
    subheading: "Master Financial Strategy at the Executive Level",
    subtext: "Participants leave with a sharper financial acumen and the confidence to make high-stakes financial decisions that drive long-term business value.",
  },
  "innovation-design": {
    eyebrow: "Industry Specific",
    title: "Innovation Design into Action",
    description: "This programme equips leaders with design thinking tools and innovation methodologies to translate creative ideas into practical solutions that create real business value.",
    banner: "/images/solutions/industry-2.jpg",
    subheading: "Turn Ideas Into Impact Through Design-Led Innovation",
    subtext: "From ideation to prototyping and implementation, participants gain hands-on experience in human-centred design and agile innovation practices.",
  },
  "marketing-sales": {
    eyebrow: "Industry Specific",
    title: "Global Marketing & Sales Leadership",
    description: "A programme for marketing and sales leaders seeking to build global strategies, lead high-performance teams, and drive revenue growth in competitive international markets.",
    banner: "/images/solutions/industry-3.jpg",
    subheading: "Lead Marketing and Sales at a Global Scale",
    subtext: "Participants develop the strategic frameworks and leadership capabilities to build winning brands, engage customers, and outperform competition in global markets.",
  },
  "healthcare-leadership": {
    eyebrow: "Industry Specific",
    title: "Strategic Leadership Across Healthcare Ecosystems",
    description: "This programme prepares healthcare executives to lead complex health systems, drive clinical and operational excellence, and navigate the evolving healthcare landscape.",
    banner: "/images/solutions/industry-4.jpg",
    subheading: "Lead Healthcare Transformation with Strategic Clarity",
    subtext: "From policy to practice, this programme equips healthcare leaders with the tools to improve outcomes, manage resources, and innovate care delivery across the ecosystem.",
  },
};
